services:
  db:
    image: mysql:8.0
    container_name: employee-mysql
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      TZ: "Asia/Tokyo"
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password